In [1]:
try:
    %pip install --user "oracledb" --no-warn-script-location
except Exception as e:
    print("\x1b[31m\u2717 Unexpected error! Please contact course staff\n" +
         "Please include the entire text above and below in your message.")
    raise

Collecting oracledb
  Downloading oracledb-3.4.2-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (7.7 kB)
Requirement already satisfied: cryptography>=3.2.1 in /opt/conda/lib/python3.13/site-packages (from oracledb) (46.0.2)
Requirement already satisfied: typing_extensions>=4.14.0 in /opt/conda/lib/python3.13/site-packages (from oracledb) (4.15.0)
Requirement already satisfied: cffi>=1.14 in /opt/conda/lib/python3.13/site-packages (from cryptography>=3.2.1->oracledb) (2.0.0)
Requirement already satisfied: pycparser in /opt/conda/lib/python3.13/site-packages (from cffi>=1.14->cryptography>=3.2.1->oracledb) (2.22)
Downloading oracledb-3.4.2-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 11.1 MB/s  0:00:00 eta 0:00:01
Installing collected packages: oracledb
Successfully installed oracledb-3.4.2
Note: you may need to restart the kernel to use updated packages.

In [4]:
import oracledb
dsn = oracledb.makedsn("localhost", 1522, service_name="stu")
connection = oracledb.connect(user="ora_maggie63", password="a61851572", dsn=dsn)

cur = connection.cursor()
for row in cur.execute("select * from titles"):
    print(row)
cur.close()
connection.close()

('PC8888  ', 'Secrets of Silicon Valley', 'popular_comp', '1389', 20, ' 8000.00 ', 4095, '1', "Muckraking reporting on the world's largest computer\nhardware and software manufacturers.", '1985-06-12          ')
('BU1032  ', "The Busy Executive's Database Guide", 'business    ', '1389', 20, ' 5000.00 ', 4095, '1', 'An overview of available database systems with emphasis\n on common business applications.  Illustrated.', '1985-06-12          ')
('PS7777  ', 'Emotional Security: A New Algorithm', 'psychology  ', '0736', 8, ' 4000.00 ', 3336, '1', 'Protecting yourself and your loved ones from undue\n emotional stress in the modern world.\nUse of computer and nutritional aids emphasized.', '1985-06-12          ')
('PS3333  ', 'Prolonged Data Deprivation: Four Case Studies', 'psychology  ', '0736', 20, ' 2000.00 ', 4072, '1', 'What happens when the data runs dry?\nSearching evaluations of information-shortage effects.', '1985-06-12          ')
('BU1111  ', 'Cooking with Computers: Surreptitious Balance Sheets', 'business    ', '1389', 12, ' 5000.00 ', 3876, '1', 'Helpful hints on how to use your electronic resources\nto the best advantage.', '1985-06-09          ')
('MC2222  ', 'Silicon Valley Gastronomic Treats', 'mod_cook    ', '0877', 20, ' 0.00    ', 2032, '1', 'Favorite recipes for quick, easy, and elegant meals tried and\ntested by people who never have time to eat, let alone cook.', '1985-06-09          ')
('TC7777  ', 'Sushi, Anyone?', 'trad_cook   ', '0877', 15, ' 8000.00 ', 4095, '1', 'Detailed instructions on improving your position in life by\nlearning how to make authentic Japanese sushi in your spare time.\n5-10% increase in number of friends per recipe reported from beta test. ', '1985-06-12          ')
('TC4203  ', 'Fifty Years in Buckingham Palace Kitchens', 'trad_cook   ', '0877', 12, ' 4000.00 ', 15096, '1', "More anecdotes from the Queen's favorite cook describing life among\nEnglish royalty.  Recipes, techniques, tender vignettes.", '06/12/85            ')
('PC1035  ', 'But Is It User Friendly?', 'popular_comp', '1389', 23, ' 7000.00 ', 8780, '1', "A survey of software for the naive user, focusing on\nthe 'friendliness' of each.", '06/30/85            ')
('BU2075  ', 'You Can Combat Computer Stress!', 'business    ', '0736', 3, ' 10125.00', 18722, '1', 'The latest medical and psychological techniques for living with\nthe electronic office.  Easy-to-understand explanations.', '06/30/85            ')
('PS2091  ', 'Is Anger the Enemy?', 'psychology  ', '0736', 11, ' 2275.00 ', 2045, '1', 'Carefully researched study of the effects of strong emotions\non the body. Metabolic charts included.', '06/15/85            ')
('PS2106  ', 'Life Without Fear', 'psychology  ', '0736', 7, ' 6000.00 ', 111, '1', 'New exercise, meditation, and nutritional techniques\nthat can reduce the shock of daily interactions. Popular audience.\nSample menus included,exercise video available separately.', '10/05/85            ')
('MC3021  ', 'The Gourmet Microwave', 'mod_cook    ', '0877', 3, ' 15000.00', 22246, '1', 'Traditional French gourmet recipes\nadapted for modern microwave cooking.', '1985-06-18          ')
('TC3218  ', 'Onions, Leeks, and Garlic:\nCooking Secrets of the Mediterranean', 'trad_cook   ', '0877', 21, ' 7000.00 ', 375, '1', 'Profusely illustrated in color, this makes a wonderful\ngift book for a cuisine-oriented friend.', '1985-02-23          ')
('MC3026  ', 'The Psychology of Computer Cooking', None, '0877', None, None, None, '0', None, None)
('BU7832  ', 'Straight Talk About Computers', 'business    ', '1389', 20, ' 5000.00 ', 4095, '1', 'Annotated analysis of what computers can do for you: a no-hype\nguide for the critical user.', '1985-06-22          ')
('PS1372  ', 'Computer Phobic and Non-Phobic Individuals: Behavior Variations', 'psychology  ', '0736', 22, ' 7000.00 ', 375, '1', 'A must for the specialist, this book examines the difference\nbetween those who hate and fear computers and those who think\nthey are swell.', '1985-12-21          ')
('PC9999  ', 'Net Etiquette', 'popular_comp', '1389', None, None, None, '0', 'A must-read for computer conferencing debutantes!.', None)

In [9]:
# Import statements
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from zipfile import ZipFile

In [12]:
zip_file = ZipFile('data/movie_data.csv.zip')

tomatoes_original = pd.read_csv('data/rotten_tomatoes_movies.csv')
letterboxd_original = pd.read_csv(zip_file.open('movie_data.csv'), engine = 'python')
oscars_original = pd.read_csv('data/the_oscar_award.csv')

print(letterboxd_original.shape, tomatoes_original.shape, oscars_original.shape)

(285963, 19) (143258, 16) (11110, 8)

In [24]:
tomatoes = tomatoes_original.dropna().drop_duplicates()
good_movies = tomatoes[(tomatoes['audienceScore'] > 30) & (tomatoes['audienceScore'] > 30)]['title']
tomatoes['releaseDateTheaters'] = pd.to_datetime(tomatoes['releaseDateTheaters'])
tomatoes = tomatoes[(tomatoes['releaseDateTheaters'] >= '2015-01-01') & (tomatoes['title'].isin(good_movies))]

letterboxd = letterboxd_original.replace('[]', np.nan)
letterboxd = letterboxd.dropna().drop_duplicates()
letterboxd = letterboxd[(letterboxd['year_released'] > 2014) & (letterboxd['movie_title'].isin(good_movies))]

oscars = oscars_original.dropna().drop_duplicates()
oscars = oscars[(oscars['year_film'] > 2014) & (oscars['film'].isin(good_movies))]

print(tomatoes.shape, letterboxd.shape, oscars.shape)

(655, 16) (909, 19) (465, 8)

In [18]:
letterboxd.head()

,_id,genres,image_url,imdb_id,imdb_link,movie_id,movie_title,original_language,overview,popularity,production_countries,release_date,runtime,spoken_languages,tmdb_id,tmdb_link,vote_average,vote_count,year_released
1073,5fc86a006758f69634770573,"[""Drama""]",film-poster/6/6/7/4/0/8/667408-shower-0-230-0-...,tt12927024,http://www.imdb.com/title/tt12927024/maindetails,shower-2020,Shower,de,Just letting loose – that is Samiel’s wish for...,0.840,"[""Austria""]",2020-09-27,30.0,"[""Deutsch""]",746019.0,https://www.themoviedb.org/movie/746019/,0.0,0.0,2020.0
1865,5fc86a106758f69634775c5d,"[""Drama"",""Fantasy"",""Thriller""]",film-poster/3/4/3/6/5/6/343656-the-call-0-230-...,tt5253866,http://www.imdb.com/title/tt5253866/maindetails,lappel,The Call,fr,"Benoît, 50, is a police lieutenant wounded by ...",0.657,"[""France"",""Spain""]",2015-06-13,17.0,"[""Français""]",409412.0,https://www.themoviedb.org/movie/409412/,7.5,2.0,2015.0
2324,5fc86a1e6758f6963477b6b2,"[""Action"",""Adventure"",""Comedy"",""Fantasy"",""Scie...",film-poster/2/0/9/3/8/2/209382-thor-ragnarok-0...,tt3501632,http://www.imdb.com/title/tt3501632/maindetails,thor-ragnarok,Thor: Ragnarok,en,Thor is imprisoned on the other side of the un...,125.417,"[""United States of America""]",2017-10-25,131.0,"[""English""]",284053.0,https://www.themoviedb.org/movie/284053/,7.6,16704.0,2017.0
2882,5fc86a2d6758f69634781b86,"[""Drama"",""History""]",film-poster/2/4/6/0/1/6/246016-the-young-messi...,tt1002563,http://www.imdb.com/title/tt1002563/maindetails,the-young-messiah,The Young Messiah,en,Tells the story of Jesus Christ at age seven a...,17.203,"[""United States of America""]",2016-03-10,120.0,"[""English""]",318850.0,https://www.themoviedb.org/movie/318850/,6.3,93.0,2016.0
3106,5fc86a3d6758f696347876f8,"[""Drama"",""Action"",""History""]",film-poster/3/3/0/3/6/4/330364-only-the-brave-...,tt3829920,http://www.imdb.com/title/tt3829920/maindetails,only-the-brave-2017,Only the Brave,en,Members of the Granite Mountain Hotshots battl...,22.355,"[""United States of America""]",2017-09-22,134.0,"[""English""]",395991.0,https://www.themoviedb.org/movie/395991/,7.3,1123.0,2017.0

In [19]:
tomatoes.head()

,id,title,audienceScore,tomatoMeter,rating,ratingContents,releaseDateTheaters,releaseDateStreaming,runtimeMinutes,genre,originalLanguage,director,writer,boxOffice,distributor,soundMix
146,robin_hood_2018,Robin Hood,40.0,15.0,PG-13,"['Extended Sequences of Violence', 'Action', '...",2018-11-21,2019-02-19,118.0,"Action, Adventure",English,Otto Bathurst,"Ben Chandler,David James Kelly",$30.8M,Lionsgate Films,Dolby Atmos
273,west_side_story_2021,West Side Story,93.0,91.0,PG-13,"['Some Strong Violence', 'Brief Smoking', 'Str...",2021-12-10,2022-03-02,156.0,"Musical, Romance",English,Steven Spielberg,Tony Kushner,$38.5M,20th Century Studios,"Dolby Digital, Dolby Atmos"
308,youth_2015,Youth,69.0,71.0,R,"['Language', 'Graphic Nudity', 'Some Sexuality']",2015-12-04,2016-03-01,118.0,Drama,English,Paolo Sorrentino,Paolo Sorrentino,$2.7M,Fox Searchlight,Dolby Atmos
468,jurassic_world_dominion,Jurassic World Dominion,77.0,29.0,PG-13,"['Language', 'Intense Sequences of Action', 'S...",2022-06-10,2022-09-02,147.0,"Action, Adventure, Sci-fi, Mystery & thriller",English,Colin Trevorrow,"Emily Carmichael,Colin Trevorrow",$376.0M,Universal Pictures,"Dolby Digital, Dolby Atmos"
717,black_adam,Black Adam,88.0,39.0,PG-13,"['Sequences of Strong Violence', 'Intense Acti...",2022-10-21,2022-11-22,125.0,"Action, Adventure, Fantasy",English,Jaume Collet-Serra,"Adam Sztykiel,Rory Haines,Sohrab Noshirvani",$168.1M,Warner Bros. Pictures,"Dolby Digital, Dolby Atmos"

In [20]:
oscars.head()

,year_film,year_ceremony,ceremony,category,canon_category,name,film,winner
9861,2015,2016,88,ACTOR IN A LEADING ROLE,ACTOR IN A LEADING ROLE,Matt Damon,The Martian,False
9862,2015,2016,88,ACTOR IN A LEADING ROLE,ACTOR IN A LEADING ROLE,Leonardo DiCaprio,The Revenant,True
9866,2015,2016,88,ACTOR IN A SUPPORTING ROLE,ACTOR IN A SUPPORTING ROLE,Tom Hardy,The Revenant,False
9868,2015,2016,88,ACTOR IN A SUPPORTING ROLE,ACTOR IN A SUPPORTING ROLE,Mark Rylance,Bridge of Spies,True
9869,2015,2016,88,ACTOR IN A SUPPORTING ROLE,ACTOR IN A SUPPORTING ROLE,Sylvester Stallone,Creed,False