In [1]:
try:
    %pip install --user "oracledb" --no-warn-script-location
except Exception as e:
    print("\x1b[31m\u2717 Unexpected error! Please contact course staff\n" +
         "Please include the entire text above and below in your message.")
    raise

Requirement already satisfied: oracledb in /home/jupyter/.local/lib/python3.13/site-packages (3.4.2)
Requirement already satisfied: cryptography>=3.2.1 in /opt/conda/lib/python3.13/site-packages (from oracledb) (46.0.2)
Requirement already satisfied: typing_extensions>=4.14.0 in /opt/conda/lib/python3.13/site-packages (from oracledb) (4.15.0)
Requirement already satisfied: cffi>=1.14 in /opt/conda/lib/python3.13/site-packages (from cryptography>=3.2.1->oracledb) (2.0.0)
Requirement already satisfied: pycparser in /opt/conda/lib/python3.13/site-packages (from cffi>=1.14->cryptography>=3.2.1->oracledb) (2.22)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import oracledb
dsn = oracledb.makedsn("localhost", 1522, service_name="stu")
connection = oracledb.connect(user="ora_maggie63", password="a61851572", dsn=dsn)

cur = connection.cursor()
for row in cur.execute("select * from titles"):
    print(row)
cur.close()
connection.close()

('PC8888  ', 'Secrets of Silicon Valley', 'popular_comp', '1389', 20, ' 8000.00 ', 4095, '1', "Muckraking reporting on the world's largest computer\nhardware and software manufacturers.", '1985-06-12          ')
('BU1032  ', "The Busy Executive's Database Guide", 'business    ', '1389', 20, ' 5000.00 ', 4095, '1', 'An overview of available database systems with emphasis\n on common business applications.  Illustrated.', '1985-06-12          ')
('PS7777  ', 'Emotional Security: A New Algorithm', 'psychology  ', '0736', 8, ' 4000.00 ', 3336, '1', 'Protecting yourself and your loved ones from undue\n emotional stress in the modern world.\nUse of computer and nutritional aids emphasized.', '1985-06-12          ')
('PS3333  ', 'Prolonged Data Deprivation: Four Case Studies', 'psychology  ', '0736', 20, ' 2000.00 ', 4072, '1', 'What happens when the data runs dry?\nSearching evaluations of information-shortage effects.', '1985-06-12          ')
('BU1111  ', 'Cooking with Computers: Surreptitious Balance Sheets', 'business    ', '1389', 12, ' 5000.00 ', 3876, '1', 'Helpful hints on how to use your electronic resources\nto the best advantage.', '1985-06-09          ')
('MC2222  ', 'Silicon Valley Gastronomic Treats', 'mod_cook    ', '0877', 20, ' 0.00    ', 2032, '1', 'Favorite recipes for quick, easy, and elegant meals tried and\ntested by people who never have time to eat, let alone cook.', '1985-06-09          ')
('TC7777  ', 'Sushi, Anyone?', 'trad_cook   ', '0877', 15, ' 8000.00 ', 4095, '1', 'Detailed instructions on improving your position in life by\nlearning how to make authentic Japanese sushi in your spare time.\n5-10% increase in number of friends per recipe reported from beta test. ', '1985-06-12          ')
('TC4203  ', 'Fifty Years in Buckingham Palace Kitchens', 'trad_cook   ', '0877', 12, ' 4000.00 ', 15096, '1', "More anecdotes from the Queen's favorite cook describing life among\nEnglish royalty.  Recipes, techniques, tender vignettes.", '06/12/85            ')
('PC1035  ', 'But Is It User Friendly?', 'popular_comp', '1389', 23, ' 7000.00 ', 8780, '1', "A survey of software for the naive user, focusing on\nthe 'friendliness' of each.", '06/30/85            ')
('BU2075  ', 'You Can Combat Computer Stress!', 'business    ', '0736', 3, ' 10125.00', 18722, '1', 'The latest medical and psychological techniques for living with\nthe electronic office.  Easy-to-understand explanations.', '06/30/85            ')
('PS2091  ', 'Is Anger the Enemy?', 'psychology  ', '0736', 11, ' 2275.00 ', 2045, '1', 'Carefully researched study of the effects of strong emotions\non the body. Metabolic charts included.', '06/15/85            ')
('PS2106  ', 'Life Without Fear', 'psychology  ', '0736', 7, ' 6000.00 ', 111, '1', 'New exercise, meditation, and nutritional techniques\nthat can reduce the shock of daily interactions. Popular audience.\nSample menus included,exercise video available separately.', '10/05/85            ')
('MC3021  ', 'The Gourmet Microwave', 'mod_cook    ', '0877', 3, ' 15000.00', 22246, '1', 'Traditional French gourmet recipes\nadapted for modern microwave cooking.', '1985-06-18          ')
('TC3218  ', 'Onions, Leeks, and Garlic:\nCooking Secrets of the Mediterranean', 'trad_cook   ', '0877', 21, ' 7000.00 ', 375, '1', 'Profusely illustrated in color, this makes a wonderful\ngift book for a cuisine-oriented friend.', '1985-02-23          ')
('MC3026  ', 'The Psychology of Computer Cooking', None, '0877', None, None, None, '0', None, None)
('BU7832  ', 'Straight Talk About Computers', 'business    ', '1389', 20, ' 5000.00 ', 4095, '1', 'Annotated analysis of what computers can do for you: a no-hype\nguide for the critical user.', '1985-06-22          ')
('PS1372  ', 'Computer Phobic and Non-Phobic Individuals: Behavior Variations', 'psychology  ', '0736', 22, ' 7000.00 ', 375, '1', 'A must for the specialist, this book examines the difference\nbetween those who hate and fear computers and those who think\nthey are swell.', '1985-12-21          ')
('PC9999  ', 'Net Etiquette', 'popular_comp', '1389', None, None, None, '0', 'A must-read for computer conferencing debutantes!.', None)

In [3]:
# Import statements
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from zipfile import ZipFile

In [40]:
zip_file = ZipFile('data/movie_data.csv.zip')

tomatoes_original = pd.read_csv('data/rotten_tomatoes_movies.csv')
letterboxd_original = pd.read_csv(zip_file.open('movie_data.csv'), engine = 'python')
oscars_original = pd.read_csv('data/the_oscar_award.csv')

print(letterboxd_original.shape, tomatoes_original.shape, oscars_original.shape)

(285963, 19) (143258, 16) (11110, 8)

In [41]:
drop_tomatoes = ['id', 'rating', 'ratingContents', 'releaseDateStreaming', 'runtimeMinutes', 'director', 'writer', 'distributor', 'soundMix']
good_movies = tomatoes[(tomatoes['audienceScore'] > 50) | (tomatoes['tomatoMeter'] > 50)]['title']
tomatoes = tomatoes_original.drop(columns = drop_tomatoes).dropna().drop_duplicates()
tomatoes['releaseDateTheaters'] = pd.to_datetime(tomatoes['releaseDateTheaters'])
tomatoes = tomatoes[(tomatoes['releaseDateTheaters'] >= '2015-01-01') & (tomatoes['title'].isin(good_movies))]

drop_letterboxd = ['_id', 'image_url', 'imdb_id', 'imdb_link', 'movie_id', 'overview', 'runtime', 'tmdb_id', 'tmdb_link']
letterboxd = letterboxd_original.replace('[]', np.nan)
letterboxd = letterboxd.drop(columns = drop_letterboxd).dropna().drop_duplicates()
letterboxd = letterboxd[(letterboxd['year_released'] > 2014) & (letterboxd['movie_title'].isin(good_movies))]

drop_oscars = ['category']
oscars = oscars_original.drop(columns = drop_oscars).dropna().drop_duplicates()
oscars = oscars[(oscars['year_film'] > 2014) & (oscars['film'].isin(good_movies))]

print(tomatoes.shape, letterboxd.shape, oscars.shape)

(1569, 7) (1470, 10) (585, 7)

In [42]:
letterboxd.head()

,genres,movie_title,original_language,popularity,production_countries,release_date,spoken_languages,vote_average,vote_count,year_released
54,"[""Drama""]",In the Shadow of Women,fr,2.636,"[""Switzerland"",""France""]",2015-05-14,"[""Français""]",6.0,37.0,2015.0
67,"[""Drama""]",Sollers Point,en,2.193,"[""France"",""United States of America""]",2017-10-19,"[""English""]",5.6,15.0,2017.0
154,"[""Thriller"",""Horror"",""Mystery""]",The Dead Center,en,4.165,"[""United States of America""]",2019-10-11,"[""English""]",5.6,43.0,2018.0
243,"[""Drama"",""Romance""]",The Photograph,en,7.987,"[""United States of America""]",2020-02-14,"[""English""]",6.6,154.0,2020.0
735,"[""Documentary""]",The Work,en,3.634,"[""United States of America""]",2017-03-11,"[""English""]",7.8,22.0,2017.0

In [43]:
tomatoes

,title,audienceScore,tomatoMeter,releaseDateTheaters,genre,originalLanguage,boxOffice
134,Endless Poetry,80.0,93.0,2017-07-14,Biography,Spanish,$64.0K
273,West Side Story,93.0,91.0,2021-12-10,"Musical, Romance",English,$38.5M
308,Youth,69.0,71.0,2015-12-04,Drama,English,$2.7M
449,Censored Voices,68.0,90.0,2015-11-20,"Documentary, History, Drama",Hebrew,$34.2K
524,Skate Kitchen,76.0,89.0,2018-08-10,Drama,English,$236.1K
...,...,...,...,...,...,...,...
142722,Buffaloed,60.0,81.0,2020-02-14,Comedy,English,$29.0K
142977,Best Worst Thing That Ever Could Have Happened,78.0,95.0,2016-11-18,Documentary,English,$104.0K
143013,Wait for Your Laugh,98.0,89.0,2017-11-03,Documentary,English,$17.6K
143087,First Love,88.0,98.0,2019-09-27,"Crime, Drama, Comedy",Japanese,$218.3K
143165,SHOT! The Psycho-Spiritual Mantra of Rock,45.0,94.0,2017-04-07,"Documentary, Music",English,$14.0K

In [44]:
oscars.head()

,year_film,year_ceremony,ceremony,canon_category,name,film,winner
9861,2015,2016,88,ACTOR IN A LEADING ROLE,Matt Damon,The Martian,False
9862,2015,2016,88,ACTOR IN A LEADING ROLE,Leonardo DiCaprio,The Revenant,True
9863,2015,2016,88,ACTOR IN A LEADING ROLE,Michael Fassbender,Steve Jobs,False
9865,2015,2016,88,ACTOR IN A SUPPORTING ROLE,Christian Bale,The Big Short,False
9866,2015,2016,88,ACTOR IN A SUPPORTING ROLE,Tom Hardy,The Revenant,False