In [23]:
import pandas as pd
import os
os.makedirs("cpsc368_group19/generated", exist_ok=True)

In [15]:
tomatoes = pd.read_csv("cpsc368_group19/data/tomatoes_clean.csv")
oscars = pd.read_csv("cpsc368_group19/data/oscars_clean.csv")
letterboxd = pd.read_csv("cpsc368_group19/data/letterboxd_clean.csv")

In [16]:
movies_df = tomatoes[['title', 'releaseDateTheaters', 'genre', 'originalLanguage']].copy()

movies_df = movies_df.rename(columns={
    'releaseDateTheaters': 'releaseDate',
    'originalLanguage': 'language'
})

movies_df.head()

                  title releaseDate           genre language
0                Violet  2017-05-12           Drama    Dutch
1  Small Town Wisconsin  2022-06-03   Comedy, Drama  English
2        Endless Poetry  2017-07-14       Biography  Spanish
3             Elephants  2018-12-07  Romance, Drama  English
4             Unbranded  2015-09-25     Documentary  English

In [18]:
metrics_df = tomatoes[['title','audienceScore','tomatoMeter']].copy()

In [19]:
metrics_df = metrics_df.merge(
    letterboxd[['movie_title','popularity','vote_average','vote_count']],
    left_on='title',
    right_on='movie_title',
    how='left'
)

metrics_df = metrics_df.drop(columns=['movie_title'])

metrics_df.head()

,title,audienceScore,tomatoMeter,popularity,vote_average,vote_count
0,Violet,56.0,85.0,17.504,5.0,2.0
1,Small Town Wisconsin,88.0,83.0,2.640,6.5,2.0
2,Endless Poetry,80.0,93.0,8.424,7.6,136.0
3,Elephants,95.0,83.0,1.018,6.5,2.0
4,Unbranded,83.0,75.0,3.496,6.9,16.0

In [20]:
oscars_df = oscars.copy()

oscars_df['title'] = oscars_df['film']

oscars_df = oscars_df[
    ['year_film','year_ceremony','ceremony','canon_category','name','title','winner']
]

oscars_df = oscars_df.reset_index(drop=True)

oscars_df['nomination_id'] = oscars_df.index + 1

oscars_df.head()

,year_film,year_ceremony,ceremony,canon_category,name,title,winner,nomination_id
0,2015,2016,88,ACTOR IN A LEADING ROLE,Matt Damon,The Martian,False,1
1,2015,2016,88,ACTOR IN A LEADING ROLE,Leonardo DiCaprio,The Revenant,True,2
2,2015,2016,88,ACTOR IN A LEADING ROLE,Michael Fassbender,Steve Jobs,False,3
3,2015,2016,88,ACTOR IN A SUPPORTING ROLE,Christian Bale,The Big Short,False,4
4,2015,2016,88,ACTOR IN A SUPPORTING ROLE,Tom Hardy,The Revenant,False,5

In [28]:
movies_df.to_csv("cpsc368_group19/generated/movies_table.csv", index=False)
metrics_df.to_csv("cpsc368_group19/generated/movie_metrics_table.csv", index=False)
oscars_df.to_csv("cpsc368_group19/generated/oscar_nominations_table.csv", index=False)

In [29]:
!git add cpsc368_group19/schema_table/
!git commit -m "Create schema tables for Movies, Metrics, OscarNominations"
!git push

fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).